### ISSUE TITLE
Page transition broken with nuxt-i18n

### ISSUE THREAD

**Issue by thariddler** [nuxt-community/nuxt-i18n#150]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://github.com](https://github.com)

### Steps to reproduce

I have simple fade page transition

```css
.page-enter-active {
  backface-visibility: hidden;
  will-change: opacity;
  opacity: 1;
  transition: opacity 450ms linear;
}

.page-leave-active {
  backface-visibility: hidden;
  will-change: opacity;
  opacity: 1;
  transition: opacity 450ms linear;
}

.page-enter {
  opacity: 0;
}

.page-leave-active {
  opacity: 0;
}
```

The problem is, when I change locale, text content changes **instantly** while page transition is not complete. 
In result I have a blink of content. 

Is there'a a way to solve this? 

### What is expected ?

No blink, smooth transition

### What is actually happening?

Transition broken, content blink

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c163">#c163</a>)</em></sub></div>
