### ISSUE TITLE
The title in head is blink when change locale

### ISSUE THREAD

**Issue by thariddler** [nuxt-community/nuxt-i18n#151]
### Version

[v5.3.0](https://github.com/nuxt-i18n/releases/tag/v5.3.0)

### Reproduction link

[https://github.com](https://github.com)

### Steps to reproduce

I set my `head()` in `index.vue`. The problem is when I change locale or navigate to another route I see `title` blink.

If I remove `nuxt-i18n` or set `seo: false` everything ok.

```js
head () {
  title: `!!MY TITLE`
}
```

![output.gif](https://cmty.s3.eu-west-1.amazonaws.com/110467581/9f13a0a0-de25-11e8-8f7d-7309c28391ba.gif)

### What is expected ?

No blink

### What is actually happening?

Blink

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c165">#c165</a>)</em></sub></div>

**Comment by thariddler** [comment]
Looks like this is Nuxt page transition issue somewhere

**Comment by thariddler** [comment]
Just double checked from scratch on blank Nuxt app. This is `nuxt-i18n` issue.

**Comment by thariddler** [comment]
If I set `seo: false` then there's no issue. But what if I need SEO?

**Comment by adi-zz** [comment]
@thariddler, is it possible that this issue is in fact caused by https://github.com/kazupon/vue-i18n/issues/408?

**Comment by thariddler** [comment]
Forgot to mention, to reproduce this issue you need long page transitions

```css
.page-enter-active {
  opacity: 1;
  transition: opacity 1000ms linear;
}

.page-leave-active {
  opacity: 1;
  transition: opacity 1000ms linear;
}

.page-enter {
  opacity: 0;
}

.page-leave-active {
  opacity: 0;
}
```

If you have no transition then it's happening instantly and you will not notice the issue.

@adi-zz not sure! It could be because `head()` manipulation is triggered in wrong time n=by this module and it's conflicting with custom `head()` in pages.
